[package]
name = "tari"
version = "0.0.1"
authors = [""]
edition = "2021"


[dependencies]
nanos_sdk = { git = "https://github.com/LedgerHQ/ledger-nanos-sdk.git" }
nanos_ui = { git = "https://github.com/LedgerHQ/ledger-nanos-ui.git" }
curve25519-dalek = {git = "https://github.com/swvheerden/curve25519-dalek", rev = "c8120bbb67c0c93da45710edae36db98e8036cbf", default-features = false}
tari_crypto = { git = "https://github.com/swvheerden/tari-crypto.git",  rev = "78f65e49412f13bc316644f0fb4451af508b9a9c", default-features = false, features = ["no_std"]}
#bulletproofs_plus = { package = "tari_bulletproofs_plus", git = "https://github.com/swvheerden/bulletproofs-plus", rev = "240a840473f9f8d9946e21ebf6d510e8f80450cf", default-features = false}
digest = { version = "0.10", default-features = false }

#bulletproofs_plus = { package = "tari_bulletproofs_plus", git = "https://github.com/swvheerden/bulletproofs-plus", rev = "240a840473f9f8d9946e21ebf6d510e8f80450cf", default-features = false, features = ["no_std"]}
#bulletproofs = { package = "tari_bulletproofs", git = "https://github.com/swvheerden/bulletproofs", rev = "6cf441b9f7a92207ff941b2513de98b85ba5dfa5", default-features = false, features = ["yoloproofs", "alloc"] }
#lazy_static = {git = "https://github.com/rust-lang-nursery/lazy-static.rs.git", rev= "e83d664", default-features = false, features = ["spin_no_std"]}
sha3 = { version = "0.10.6", default-features = false }
#tari_utilities = { git = "https://github.com/swvheerden/tari_utilities.git", rev = "be307079df67a69a8c8e658accaf0ce806a2e48f", default-features = false }
#once_cell = {version="1.8.0", default-features = false}
rand_core = {version = "0.6", default-features = false}
#blake2 = {version="0.10.6", default-features = false}
#digest = {version= "0.10", default-features = false}
embedded-alloc = "0.5.0"

critical-section = { version = "1.1.1" }
[profile.release]
opt-level = 's'
lto = true
panic = "abort"

[package.metadata.nanos]
name = "Tari"
curve = [""]
flags = "0"
icon = "key_16x16.gif"
icon_small = "key_14x14.gif"
path = [""]
